name: blender_next
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  archive: ^4.0.2
  debounce_throttle: ^2.0.0
  dio: ^5.7.0
  drift: ^2.23.0
  drift_flutter: ^0.2.3
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lucide: ^1.6.1
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  html: ^0.15.5
  intl: any
  logger: ^2.5.0
  path_provider: ^2.1.5
  pointer_interceptor: ^0.10.1+2
  signals: ^6.0.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.23.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
